services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: core_organizational_roadmap_experience
    container_name: core_organizational_roadmap_experience
    ports:
      - "3000:3000"
    volumes:
      - .:/rails:Z
    command: bash -c "bin/rails db:migrate && bin/rails server -b 0.0.0.0"
    entrypoint: /rails/bin/docker-entrypoint
    tty: true
    stdin_open: true
    environment:
      - RAILS_ENV=development
      - RAILS_SERVE_STATIC_FILES=true
